name: my_project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  device_preview: ^1.2.0
  flutter_svg: ^1.1.6
  smooth_page_indicator: ^1.0.0
  flutter_otp_text_field: ^1.4.0+2
#  intl_phone_number_input: ^0.7.0+2 # this package conflicts with ios
  country_picker: ^2.0.15
  flutter_launcher_icons: ^0.14.3
  percent_indicator: ^4.2.4
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  flutter_spinkit: ^5.2.0
  shimmer: ^2.0.0
  showcaseview: ^3.0.0
  dropdown_search: ^5.0.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^5.0.0
  flutter_screenutil: ^5.9.3
  intl_phone_field: ^3.2.0
  country_code_picker: ^3.1.0
  animated_custom_dropdown: 3.1.1
  image_picker: ^1.1.2
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  flutter_local_notifications: any
  dropdown_button2: ^2.3.9
  file_picker: ^10.1.2
  dynamic_tabbar: ^1.0.9
  webview_flutter: ^4.10.0
  skeletonizer: ^2.1.0+1
  http: ^1.3.0
  path: ^1.7.0
  http_parser: ^4.0.0
  flutter_html: ^3.0.0-beta.2
  pin_code_fields: ^8.0.1
  lottie: ^3.3.1
  provider: ^6.1.2
  flutter_keyboard_visibility: ^6.0.0
  pdf: ^3.11.3
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  cross_file: ^0.3.4+2
  cached_network_image: ^3.4.1
  local_auth: ^2.1.8
  flutter_animate: ^4.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  uni_country_city_picker: ^1.0.2
  mockito: ^5.4.6
  build_runner: ^2.4.15

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/images/empty.json
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 700




